name: finetune-lm

dependencies:
  - datasets
  - pandas
  - pip
  - python >=3.12
  - pytorch
  - tqdm
  - transformers
  - optuna
  - seaborn
  - PyPDF2
  - plotly
  - scikit-learn
  - pip:
      - sball
      - kaleido
